// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQeNhe1aKaHricR9ntDUxwdEKlEe7KRY',
    appId: '1:650138842464:web:f6164ed5ce516628aa5a05',
    messagingSenderId: '650138842464',
    projectId: 'reserva-espacos',
    authDomain: 'reserva-espacos.firebaseapp.com',
    storageBucket: 'reserva-espacos.firebasestorage.app',
    measurementId: 'G-J1YCY87DFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5H124bT7VTvWrSoNM6Ex1m0JQVIMI9gU',
    appId: '1:650138842464:android:38630fef2b44d625aa5a05',
    messagingSenderId: '650138842464',
    projectId: 'reserva-espacos',
    storageBucket: 'reserva-espacos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzKJYcns9agZpU5eHrOnjb-i7B5wGd6qk',
    appId: '1:650138842464:ios:d62b9bc5f4b13c74aa5a05',
    messagingSenderId: '650138842464',
    projectId: 'reserva-espacos',
    storageBucket: 'reserva-espacos.firebasestorage.app',
    iosBundleId: 'com.example.reservaEspacos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQeNhe1aKaHricR9ntDUxwdEKlEe7KRY',
    appId: '1:650138842464:web:8722cd5d06872dc2aa5a05',
    messagingSenderId: '650138842464',
    projectId: 'reserva-espacos',
    authDomain: 'reserva-espacos.firebaseapp.com',
    storageBucket: 'reserva-espacos.firebasestorage.app',
    measurementId: 'G-GJ5PR0CBLK',
  );

}